name = "powerjoular"
description = "Monitoring the power consumption of multiple platforms and processes"
version = "1.0.1"

authors = ["Adel Noureddine"]
maintainers = ["Adel Noureddine <adel.noureddine@outlook.com>"]
maintainers-logins = ["adelnoureddine"]

tags = ["linux", "power", "energy"]

licenses = "GPL-3.0-only"
website = "https://www.noureddine.org/research/joular/powerjoular"

executables = ["powerjoular"]

[origin]
commit = "ba08a0ae54561da34b1c7976966afe1edc7221e6"
url = "git+https://github.com/joular/powerjoular.git"

